Minimal IRTranslator + additional Legalization
llvm-pic/llvm-pic pull request #63
Opened 2024-03-31 13:54 UTC by indicatelovelace

See #34 for IRTranslator. Cannot close, since this mainly involves a calling convention.

Legalization #33 is implemented. Minimal definition according to [Legalizer][https://llvm.org/docs/GlobalISel/Legalizer.html] are defined, even if there is not of yet a clear path to selection, e.g. G_FRAME_INDEX.
Besides minimal instructions, additional instructions where implemented that can be easily selected / have an implemented selection. Includes some legalization of control flow instructions #61.

Additionally, Load and Store selection was implemented (probably needs to be changed in the future).

2024-04-07 16:09 UTC, handiener approved these changes

2024-04-07 16:19 UTC, pr1metine requested changes
Nice. Nitpicking but pls add headers and tests

2024-04-07 16:19 UTC, pr1metine commented on llvm/lib/Target/PICMid/PICMidCallLowering.h
> +#ifndef LLVM_LIB_TARGET_PICMID_PICMIDCALLLOWERING_H
Pls add a header

2024-04-07 16:19 UTC, pr1metine commented on llvm/lib/Target/PICMid/PICMidCallLowering.cpp
> +#include "PICMidCallLowering.h"
Pls add an header

2024-05-15 16:47 UTC, pr1metine requested changes

2024-05-15 16:47 UTC, pr1metine commented on llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp
> +  const auto &TLIfalse = *MF->getSubtarget().getTargetLowering();
please rename to TLI

2024-05-15 16:47 UTC, pr1metine commented on llvm/lib/CodeGen/GlobalISel/IRTranslator.cpp
Looks like you accidentally formatted this file. Can you unformat it so that I can see what you actually changed?

2024-05-15 16:47 UTC, pr1metine commented on llvm/lib/Target/PICMid/GISel/PICMidInstructionSelector.cpp
> +bool PICMidInstructionSelector::selectFrameIndex(MachineInstr &I) const {
IIRC, there‘s also a method in PICMidRegisterInfo which resolves frame indices. Need to follow up on that

2024-06-01 13:32 UTC, pr1metine commented on llvm/lib/Target/PICMid/GISel/PICMidInstructionSelector.cpp
> +bool PICMidInstructionSelector::selectFrameIndex(MachineInstr &I) const {
https://github.com/llvm-pic/llvm-pic/blob/a87b349293a8dc5699bd2492b492370ffd2d5867/llvm/lib/Target/PICMid/PICMidRegisterInfo.cpp#L48

2024-08-28 19:27 UTC, pr1metine approved these changes
LGTM now

2024-08-28 19:27 UTC, merged